import{S as w,N as C,a as d}from"./assets/vendor-Bqcn7g4X.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const i of s)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function t(s){const i={};return s.integrity&&(i.integrity=s.integrity),s.referrerPolicy&&(i.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?i.credentials="include":s.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(s){if(s.ep)return;s.ep=!0;const i=t(s);fetch(s.href,i)}})();const n={openMobileMenuBtn:document.querySelector(".header-mobile-menu"),closeMobileMenuBtn:document.querySelector(".mobile-menu-close"),mobileMenuModal:document.querySelector(".mobile-menu-modal"),booksCategoriesList:document.querySelector(".books-categories-list"),booksCategoriesSelect:document.querySelector(".books-categories-select"),booksList:document.querySelector(".books-list"),booksShowMoreBtn:document.querySelector(".books-item-show-more"),booksCount:document.querySelector(".books-info")};function b(){n.mobileMenuModal.classList.remove("is-open"),document.body.classList.remove("no-scroll"),n.closeMobileMenuBtn.removeEventListener("click",b),n.openMobileMenuBtn.addEventListener("click",f),document.removeEventListener("keydown",g),n.mobileMenuModal.removeEventListener("click",y),n.openMobileMenuBtn.focus()}function f(){n.mobileMenuModal.classList.add("is-open"),document.body.classList.add("no-scroll"),n.closeMobileMenuBtn.focus(),n.closeMobileMenuBtn.addEventListener("click",b),n.openMobileMenuBtn.removeEventListener("click",f),document.addEventListener("keydown",g),n.mobileMenuModal.addEventListener("click",y)}function g(e){e.key==="Escape"&&b()}function y(e){e.target.classList.contains("mobile-menu-link")&&b()}n.openMobileMenuBtn.addEventListener("click",f);new w(".swiper",{modules:[C],navigation:{nextEl:".hero-button-next",prevEl:".hero-button-prev"}});d.defaults.baseURL="https://books-backend.p.goit.global/books";async function S(){try{return(await d.get("/category-list")).data}catch{return[]}}async function M(e){try{return(await d.get(`/category?category=${e}`)).data}catch{return[]}}async function m(){try{return(await d.get("/top-books")).data}catch{return[]}}function h(e,o){const t=e.map(({book_image:r,title:s,author:i,price:l})=>{const p=l?Math.ceil(Number(l)):"";return`
        <li class="books-item">
          <img src="${r}" alt="${s} cover" class="books-item-image" />
          <div class="books-item-info">
            <div class="books-item-info-left">
              <h4 class="books-item-title">${s}</h4>
              <p class="books-item-author">${i}</p>
            </div>
            <p class="books-item-price">${p?`$${p}`:"—"}</p>
          </div>
          <button type="button" class="books-item-open-modal">
            learn more
          </button>
        </li>
      `}).join("");o.insertAdjacentHTML("beforeend",t)}function E(e){const o=['<li data-category="all" class="active">All categories</li>',...e.filter(t=>t.list_name).map(t=>`<li data-category="${t.list_name}">${t.list_name}</li>`)].join("");n.booksCategoriesList.innerHTML=o}function $(e){const o=['<option value="" selected disabled hidden>Categories</option>','<option value="all">All categories</option>',...e.filter(t=>t.list_name).map(t=>`<option value="${t.list_name}">${t.list_name}</option>`)].join("");n.booksCategoriesSelect.innerHTML=o}function A(){n.booksShowMoreBtn.classList.remove("is-hidden")}function L(){n.booksShowMoreBtn.classList.add("is-hidden")}let c=[],a=window.innerWidth<768?10:24;const v=4;function q(e){c=e,a=window.innerWidth<768?10:24}function N(){a+=v}async function P(){try{const e=await S();E(e),$(e)}catch(e){console.error("Ошибка загрузки категорий:",e)}}function T(){n.booksList.innerHTML="";const e=c.slice(0,a);h(e,n.booksList),c.length>a?A():L()}function B(){const e=n.booksCount;if(!e)return;const o=Math.min(a,c.length);c.length===0?e.textContent="No books to show":e.textContent=`Showing ${o} of ${c.length}`}function k(e){q(e),T(),B()}function O(){const e=c.slice(a,a+v);h(e,n.booksList),N(),a>=c.length&&L(),B()}n.booksShowMoreBtn.addEventListener("click",O);function u(e){const o=new Set;return e.filter(t=>o.has(t.title)?!1:(o.add(t.title),!0))}async function _(e){try{const o=e.target.closest("li[data-category]");if(!o)return;const t=o.getAttribute("data-category");let r;t==="all"?(r=(await m()).flatMap(i=>i.books),r=u(r)):(r=await M(t),r=u(r)),k(r)}catch(o){console.error("Ошибка при выборе категории:",o)}}async function x(e){try{const o=e.target.value;let t;o==="all"?(t=(await m()).flatMap(s=>s.books),t=u(t)):(t=await M(o),t=u(t)),k(t)}catch(o){console.error("Ошибка при выборе категории через select:",o)}}P();n.booksCategoriesList.addEventListener("click",_);n.booksCategoriesSelect.addEventListener("change",x);async function j(){try{let o=(await m()).flatMap(t=>t.books);o=u(o),k(o)}catch(e){console.error("Ошибка загрузки книг при запуске страницы:",e)}}j();
//# sourceMappingURL=index.js.map
